#! /bin/csh -f

set libpath = /cbcl/local64/matlab_r2009a/bin/glnxa64:/cbcl/local64/matlab_r2009a/sys/os/glnxa64:/usr/local/cuda/lib

set cnsdir = `dirname $cwd`

setenv LD_LIBRARY_PATH $libpath
./demoeng $cnsdir
