function processTestSet(net)
% read all segmentations corresponding to a training or test set

m_file = ['/home/sturaga/saved_networks/' net '/latest.mat'];
mkdir(['/home/sturaga/exhibit/' net '/'])

in_files = {'~/net_sets/E1088/conn3/roi7_train_1', ...
			'~/net_sets/E1088/conn3/roi8_train_1', ...
			'~/net_sets/E1088/conn3/validate4_train_1', ...
			'~/net_sets/E2006/test/roi2', ...
			'~/net_sets/E2006/test/roi3', ...
			'~/net_sets/E2006/test/roi5', ...
			};
in_legendStr = {'e1088_test_roi7',...
				'e1088_train_roi8',...
				'e1088_train_validate4',...
				'e2006_roi2',...
				'e2006_roi3',...
				'e2006_roi5',...
				};

for k = 1:length(in_files),
	out_file = ['/home/sturaga/exhibit/' net '/conn_' in_legendStr{k} '.h5'];
	delete(out_file)
	cnpkg2_test_hdf5(m_file,in_files{k},out_file,'/main',[1 1 1]*175,1);
end
